---
- name: Pull down customer data from JIRA
  hosts: localhost
  connection: local
  vars:
    JIRA:
      username: "{{ lookup('env', 'JIRA_USERNAME') }}"
      password: "{{ lookup('env', 'JIRA_PASSWORD') }}"
      workspaceID: "{{ lookup('env', 'JIRA_WORKSPACEID') }}"
    ObjectTypeIDs:
      ATOM: 22
      ION: 12
      ARS-600: 35
      ARS-500: 8
      ARS-400: 14
      ARS-Redbox: 34
      ARS-KB-R: 16
      ARS-KB-H: 17
      GETAC-F110: 28
      PAN-GCS: 29
      NUC-GCS: 30
      RP-1: 31
      MC1-CPU-25: 32
      EARTH-QUARK: 33
  tasks:
  # Explicitly uses v2 of the REST API...will need updating in the future
  - name: Find all ATOMs
    uri:
      headers:
        Authorization: "Basic {{ lookup('env', 'JIRA_BASICAUTH') }}"
        Content-Type: 'application/json'
      #url: 'https://shotoverjira.atlassian.net/rest/servicedeskapi/insight/workspace'
      #url: 'https://shotoverjira.atlassian.net/jsm/insight/workspace/{{ JIRA.workspaceID }}/v1/objecttype/{{ ObjectTypeIDs.ATOM }}'
      url: 'https://shotoverjira.atlassian.net/jsm/insight/workspace/{{ JIRA.workspaceID }}/v1/objectschema/4'
      #user: '{{ JIRA.username }}'
      #password: '{{ JIRA.password }}'
      method: GET
    register: object_instances

#  - name: curl to get ATOMS
#    command: 'curl -X GET -H "X-ExperimentalApi: opt-in" -H "Content-Type: application/json" -H "Authorization: Basic YWxsZW5Ac2hvdG92ZXIuY29tOmt1TTdVemo1U3lYaDVvazlSUVpTRTBGMg==" https://shotoverjira.atlassian.net/rest/servicedeskapi/insight/workspace'
#    register: object_instances

  - name: Debug ATOMs
    debug:
      var: object_instances
