---
- name: Rotate passwords for user accounts
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    pw1: "{{ lookup('bitwarden', 'test-pw-1', field='item') }}"
    pw2: "{{ lookup('bitwarden', 'test-pw-2', field='item') }}"
    pw3: "{{ lookup('bitwarden', 'test-pw-3', field='item') }}"

  roles:
  - ansible-modules-bitwarden

  tasks:
  - name: Sync bitwarden vault
    command: bw sync

#  - name: Print ID
#    debug:
#      msg: "ID of {{ item.name }} is {{ item.id }}"
#    with_items: 
#    - "{{ pw1 }}"
#    - "{{ pw2 }}"
#    - "{{ pw3 }}"

  - name: Generate passwords
    command: bw generate -ulns --length 32
    with_sequence: count=4
    register: pws

  - name: Print pws data
    debug:
      msg: "PW{{ item.item }} is {{ item.stdout }}"
    loop: "{{ pws.results }}"

  - name: Create items with new pws
    command: bw get template item | jq ".name=new-test-pw-{{ item.item }} | .login=$(bw get template item.login | jq '.username=new-test-pw-{{ item.item }} | .password={{ item.stdout }}')" | bw encode | bw create item 
    loop: "{{ pws.results }}"
    register: entries

#  - name: List new bw entries
#    debug:
#      msg: "New entry #{{ item.item.item }} is {{ item.stdout }}"
#    loop: "{{ entries.results }}"
