---
- name: Update apt
  hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Update apt repo and cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: full

  - name: Remove unused packages
    apt:
      autoremove: yes

  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
      get_md5: no
    register: reboot_required_file

  - name: If reboot required, send email
    mail:
      host: smtp.gmail.com
      port: 587
      username: "{{ lookup('env', 'SMTP_USERNAME') }}"
      password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
      from: allen@shotover.com
      to: alerts@shotover.com, allen@shotover.com
      subject: Reboot required for {{ ansible_facts['hostname'] }}
      body:
        Hello,

        The host {{ ansible_facts['hostname'] }} requires a reboot after updating apt. Please reboot the host at your earliest convenience.

        Thank you,

        Mr. Roboto
    when: reboot_required_file.stat.exists
