---
- name: Update apt
  hosts: vansibl401ubu
  become: yes
  become_user: root
  tasks:
  - name: Update apt repo and cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Upgrade all packages on servers
    apt:
      upgrade: full

  - name: Remove unused packages
    apt:
      autoremove: yes

  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
      get_md5: no
    register: reboot_required_file

  - name: If reboot required, post notification to Slack
    uri:
      headers:
        Content-Type: 'application/json'
      method: POST
      body_format: json
      body: '{"text":"{{ inventory_hostname }} needs a reboot"}'
      url: "{{ lookup('env', 'ANSBL_WEBHOOK') }}"
    when: reboot_required_file.stat.exists
    no_log: true
