---
- name: Ensure services are running
  hosts: all
  #connection: local
  become: true
  tasks:
  - name: Get list of failed services
    command: systemctl --failed
    ignore_errors: true
    changed_when: false
    register: failed_services

  - name: Determine name of failed services
    debug:
      msg: "{{ failed_services.stdout | regex_search('^.* ([a-zA-Z0-9\\-]*?)\\.service', '\\1', multiline=True) }}"
    register: failed_service_names
    when: '"failed" in failed_services.stdout'

  - name: Restart failed services
    command: systemctl restart "{{ item }}"
    loop: "{{ failed_service_names.msg }}"
    changed_when: false
    when: '"failed" in failed_services.stdout'
