---
- name: Ensure services are running
  hosts: all
  become: true
  pre_tasks:
  - name: Send notification to Slack that playbook is running
    uri:
      headers:
        Content-Type: 'application/json'
      method: POST
      body_format: json
      body:
        '{
          "text": "{{ ansible_date_time.iso8601_micro }} | Running watchdog.yml"
         }'
      url: "{{ lookup('env', 'ANSBL_WEBHOOK') }}"
    when: ansible_hostname == 'vansibl401ubu'
    no_log: true

  tasks:
  - name: Get list of failed services
    command: systemctl --failed
    ignore_errors: true
    changed_when: false
    register: failed_services

  - name: Find service name
    debug:
      msg: "{{ failed_services.stdout | regex_search('^.* ([a-zA-Z0-9\\-]*?)\\.service', '\\1', multiline=True) }}"
    register: failed_service_names
    when: '"failed" in failed_services.stdout'

  - name: Restart failed services
    command: systemctl restart "{{ item }}"
    loop: "{{ failed_service_names.msg }}"
    changed_when: false
    when: '"failed" in failed_services.stdout'

  - name: Send report to Slack
    uri:
      headers:
        Content-Type: 'application/json'
      method: POST
      body_format: json
      body:
        '{
           "text": "{{ ansible_date_time.iso8601_micro }} | Restarted {{ item }} service on {{ inventory_hostname }}"
         }'
      url: "{{ lookup('env', 'ANSBL_WEBHOOK') }}"
    loop: "{{ failed_service_names.msg }}"
    when: '"failed" in failed_services.stdout'
    no_log: true
